import type {
  GameEquipmentSlot,
  GameItemDefinition,
  GameItemRewardKind,
} from '../../../shared/types';

export const GAME_ITEM_CATALOG: GameItemDefinition[] = [
  // ═══════════════════════════════════════════════
  //  Простые (simple) артефакты — без прочности
  // ═══════════════════════════════════════════════

  // ── Утилити: скорость / точность / таймер ──
  {
    id: 'steady-gloves',
    name: 'Перчатки ровного темпа',
    shortName: 'Темп',
    description: 'Чуть снижает требование к скорости и повышает коэффициент защиты.',
    rarity: 1,
    slotType: 'trinket',
    icon: 'gauge',
    rewardKind: 'simple',
    speedRequirementReductionPercent: 4,
    defCoeff: 0.08,
    effects: [
      { kind: 'speed', value: 4, unit: 'percent', description: '-4% к требуемой скорости' },
      { kind: 'defCoeff', value: 8, unit: 'percent', description: '+8% к коэфф. защиты' },
    ],
  },
  {
    id: 'focus-lens',
    name: 'Линза безошибочности',
    shortName: 'Фокус',
    description: 'Помогает удерживать точность и увеличивает шанс попадания.',
    rarity: 1,
    slotType: 'trinket',
    icon: 'eye',
    rewardKind: 'simple',
    accuracyRequirementReduction: 2,
    playerAttackBonus: 3,
    effects: [
      { kind: 'accuracy', value: 2, unit: 'percent', description: '-2% к требуемой точности' },
      { kind: 'playerAttack', value: 3, unit: 'percent', description: '+3% к шансу попасть' },
    ],
  },
  {
    id: 'path-compass',
    name: 'Компас босса',
    shortName: 'Компас',
    description: 'Добавляет время на боссах и немного снижает их защиту.',
    rarity: 1,
    slotType: 'trinket',
    icon: 'compass',
    rewardKind: 'simple',
    bossOnly: true,
    bossTimerBonusSeconds: 2,
    enemyDefenseReduction: 3,
    effects: [
      { kind: 'timer', value: 2, unit: 'seconds', description: '+2 сек. к таймеру босса' },
      { kind: 'enemyDefense', value: 3, unit: 'flat', description: '-3 к защите врагов' },
    ],
  },
  {
    id: 'whisper-feather',
    name: 'Перо легкого ритма',
    shortName: 'Перо',
    description: 'Лёгкая реликвия. Сглаживает темп и даёт небольшой бонус к криту.',
    rarity: 1,
    slotType: 'trinket',
    icon: 'feather',
    rewardKind: 'simple',
    speedRequirementReductionPercent: 3,
    critBonus: 0.02,
    effects: [
      { kind: 'speed', value: 3, unit: 'percent', description: '-3% к требуемой скорости' },
      { kind: 'critBonus', value: 2, unit: 'percent', description: '+2% к шансу крита' },
    ],
  },
  {
    id: 'line-sigil',
    name: 'Печать чистой линии',
    shortName: 'Линия',
    description: 'Два бонуса к прохождению и лёгкое усиление урона.',
    rarity: 2,
    slotType: 'trinket',
    icon: 'crosshair',
    rewardKind: 'simple',
    speedRequirementReductionPercent: 3,
    accuracyRequirementReduction: 2,
    dmgCoeff: 0.08,
    effects: [
      { kind: 'speed', value: 3, unit: 'percent', description: '-3% к требуемой скорости' },
      { kind: 'accuracy', value: 2, unit: 'percent', description: '-2% к требуемой точности' },
      { kind: 'dmgCoeff', value: 8, unit: 'percent', description: '+8% к коэфф. урона' },
    ],
  },
  {
    id: 'rabbit-step',
    name: 'След кролика',
    shortName: 'След',
    description: 'Чистая скорость и уклонение. Хорошо чувствуется в середине забега.',
    rarity: 2,
    slotType: 'trinket',
    icon: 'rabbit',
    rewardKind: 'simple',
    speedRequirementReductionPercent: 6,
    dodgeBonus: 4,
    effects: [
      { kind: 'speed', value: 6, unit: 'percent', description: '-6% к требуемой скорости' },
      { kind: 'dodge', value: 4, unit: 'percent', description: '+4% к уклонению' },
    ],
  },
  {
    id: 'radar-thread',
    name: 'Нить радара',
    shortName: 'Радар',
    description: 'Боссовый артефакт: точность, таймер и снижение защиты врагов.',
    rarity: 2,
    slotType: 'trinket',
    icon: 'radar',
    rewardKind: 'simple',
    bossOnly: true,
    accuracyRequirementReduction: 2,
    bossTimerBonusSeconds: 1,
    enemyDefenseReduction: 4,
    effects: [
      { kind: 'accuracy', value: 2, unit: 'percent', description: '-2% к требуемой точности' },
      { kind: 'timer', value: 1, unit: 'seconds', description: '+1 сек. к таймеру босса' },
      { kind: 'enemyDefense', value: 4, unit: 'flat', description: '-4 к защите врагов' },
    ],
  },
  {
    id: 'crown-oath',
    name: 'Коронный обет',
    shortName: 'Обет',
    description: 'Редкая награда: сильный боссовый бонус к прохождению и урону.',
    rarity: 3,
    slotType: 'trinket',
    icon: 'crown',
    rewardKind: 'simple',
    bossOnly: true,
    speedRequirementReductionPercent: 5,
    accuracyRequirementReduction: 3,
    dmgCoeff: 0.12,
    effects: [
      { kind: 'speed', value: 5, unit: 'percent', description: '-5% к скорости на боссе' },
      { kind: 'accuracy', value: 3, unit: 'percent', description: '-3% к точности на боссе' },
      { kind: 'dmgCoeff', value: 12, unit: 'percent', description: '+12% к коэфф. урона' },
    ],
  },
  {
    id: 'mirror-glasses',
    name: 'Зеркальные очки',
    shortName: 'Очки',
    description: 'Реликвия на точность и защиту от вражеских атак.',
    rarity: 2,
    slotType: 'trinket',
    icon: 'glasses',
    rewardKind: 'simple',
    accuracyRequirementReduction: 3,
    enemyAttackReduction: 3,
    effects: [
      { kind: 'accuracy', value: 3, unit: 'percent', description: '-3% к требуемой точности' },
      { kind: 'enemyAttack', value: 3, unit: 'flat', description: '-3 к шансу попадания врагов' },
    ],
  },
  {
    id: 'medal-of-stability',
    name: 'Медаль устойчивости',
    shortName: 'Медаль',
    description: 'Сбалансированная реликвия: скорость, точность и защита.',
    rarity: 2,
    slotType: 'trinket',
    icon: 'medal',
    rewardKind: 'simple',
    speedRequirementReductionPercent: 3,
    accuracyRequirementReduction: 2,
    defCoeff: 0.1,
    effects: [
      { kind: 'speed', value: 3, unit: 'percent', description: '-3% к требуемой скорости' },
      { kind: 'accuracy', value: 2, unit: 'percent', description: '-2% к требуемой точности' },
      { kind: 'defCoeff', value: 10, unit: 'percent', description: '+10% к коэфф. защиты' },
    ],
  },
  {
    id: 'wind-sigil',
    name: 'Печать попутного ветра',
    shortName: 'Ветер',
    description: 'Скорость и усиление урона для спокойных уровней.',
    rarity: 2,
    slotType: 'trinket',
    icon: 'wind',
    rewardKind: 'simple',
    speedRequirementReductionPercent: 6,
    dmgCoeff: 0.1,
    effects: [
      { kind: 'speed', value: 6, unit: 'percent', description: '-6% к требуемой скорости' },
      { kind: 'dmgCoeff', value: 10, unit: 'percent', description: '+10% к коэфф. урона' },
    ],
  },
  {
    id: 'blessed-bulwark',
    name: 'Благословенный бастион',
    shortName: 'Бастион',
    description: 'Боссовая реликвия: точность, таймер и защитный коэффициент.',
    rarity: 2,
    slotType: 'trinket',
    icon: 'shieldplus',
    rewardKind: 'simple',
    bossOnly: true,
    accuracyRequirementReduction: 3,
    bossTimerBonusSeconds: 2,
    defCoeff: 0.12,
    effects: [
      { kind: 'accuracy', value: 3, unit: 'percent', description: '-3% к точности на боссе' },
      { kind: 'timer', value: 2, unit: 'seconds', description: '+2 сек. к таймеру босса' },
      { kind: 'defCoeff', value: 12, unit: 'percent', description: '+12% к коэфф. защиты' },
    ],
  },

  // ── Боевые: атака / урон / защита / крит ──
  {
    id: 'viper-fang',
    name: 'Клык гадюки',
    shortName: 'Клык',
    description: 'Снижает защиту врагов и повышает коэффициент урона.',
    rarity: 2,
    slotType: 'trinket',
    icon: 'swords',
    rewardKind: 'simple',
    enemyDefenseReduction: 4,
    dmgCoeff: 0.08,
    effects: [
      { kind: 'enemyDefense', value: 4, unit: 'flat', description: '-4 к защите врагов' },
      { kind: 'dmgCoeff', value: 8, unit: 'percent', description: '+8% к коэфф. урона' },
    ],
  },
  {
    id: 'iron-carapace',
    name: 'Железный панцирь',
    shortName: 'Панцирь',
    description: 'Ослабляет атаку врагов и усиливает коэффициент защиты.',
    rarity: 2,
    slotType: 'trinket',
    icon: 'shell',
    rewardKind: 'simple',
    enemyAttackReduction: 4,
    defCoeff: 0.1,
    effects: [
      { kind: 'enemyAttack', value: 4, unit: 'flat', description: '-4 к шансу попадания врагов' },
      { kind: 'defCoeff', value: 10, unit: 'percent', description: '+10% к коэфф. защиты' },
    ],
  },
  {
    id: 'phantom-cloak',
    name: 'Плащ фантома',
    shortName: 'Плащ',
    description: 'Повышает уклонение и немного усиливает крит.',
    rarity: 2,
    slotType: 'trinket',
    icon: 'ghost',
    rewardKind: 'simple',
    dodgeBonus: 5,
    critBonus: 0.02,
    effects: [
      { kind: 'dodge', value: 5, unit: 'percent', description: '+5% к уклонению' },
      { kind: 'critBonus', value: 2, unit: 'percent', description: '+2% к шансу крита' },
    ],
  },
  {
    id: 'sharp-rune',
    name: 'Острая руна',
    shortName: 'Руна',
    description: 'Усиливает шанс попасть при атаке и коэффициент урона.',
    rarity: 1,
    slotType: 'trinket',
    icon: 'zap',
    rewardKind: 'simple',
    playerAttackBonus: 5,
    dmgCoeff: 0.06,
    effects: [
      { kind: 'playerAttack', value: 5, unit: 'percent', description: '+5% к шансу попасть' },
      { kind: 'dmgCoeff', value: 6, unit: 'percent', description: '+6% к коэфф. урона' },
    ],
  },
  {
    id: 'fury-sigil',
    name: 'Печать ярости',
    shortName: 'Ярость',
    description: 'Усиление атаки и снижение защиты врагов.',
    rarity: 2,
    slotType: 'trinket',
    icon: 'swords',
    rewardKind: 'simple',
    playerAttackBonus: 4,
    enemyDefenseReduction: 3,
    dmgCoeff: 0.06,
    effects: [
      { kind: 'playerAttack', value: 4, unit: 'percent', description: '+4% к шансу попасть' },
      { kind: 'enemyDefense', value: 3, unit: 'flat', description: '-3 к защите врагов' },
      { kind: 'dmgCoeff', value: 6, unit: 'percent', description: '+6% к коэфф. урона' },
    ],
  },
  {
    id: 'serrated-band',
    name: 'Зазубренный браслет',
    shortName: 'Браслет',
    description: 'Устойчивый бонус к меткости и плоскому урону.',
    rarity: 2,
    slotType: 'trinket',
    icon: 'activity',
    rewardKind: 'simple',
    playerAttackBonus: 7,
    playerDamageBonus: 1,
    effects: [
      { kind: 'playerAttack', value: 7, unit: 'percent', description: '+7% к шансу попасть' },
      { kind: 'playerDamage', value: 1, unit: 'flat', description: '+1 к плоскому урону' },
    ],
  },
  {
    id: 'fury-crystal',
    name: 'Кристалл ярости',
    shortName: 'Кристалл',
    description: 'Повышает коэффициент урона. Универсален и надёжен.',
    rarity: 1,
    slotType: 'trinket',
    icon: 'flame',
    rewardKind: 'simple',
    dmgCoeff: 0.15,
    effects: [
      { kind: 'dmgCoeff', value: 15, unit: 'percent', description: '+15% к коэфф. урона' },
    ],
  },
  {
    id: 'rage-pendant',
    name: 'Подвеска бешенства',
    shortName: 'Бешенство',
    description: 'Урон и снижение защиты врагов в одном предмете.',
    rarity: 2,
    slotType: 'trinket',
    icon: 'swords',
    rewardKind: 'simple',
    dmgCoeff: 0.1,
    enemyDefenseReduction: 4,
    effects: [
      { kind: 'dmgCoeff', value: 10, unit: 'percent', description: '+10% к коэфф. урона' },
      { kind: 'enemyDefense', value: 4, unit: 'flat', description: '-4 к защите врагов' },
    ],
  },
  {
    id: 'stoneskin-charm',
    name: 'Амулет каменной кожи',
    shortName: 'Камень',
    description: 'Повышает коэффициент защиты. Снижает входящий урон.',
    rarity: 1,
    slotType: 'trinket',
    icon: 'shield',
    rewardKind: 'simple',
    defCoeff: 0.15,
    effects: [
      { kind: 'defCoeff', value: 15, unit: 'percent', description: '+15% к коэфф. защиты' },
    ],
  },
  {
    id: 'guardian-ring',
    name: 'Кольцо стража',
    shortName: 'Страж',
    description: 'Защита и уклонение в одном кольце.',
    rarity: 2,
    slotType: 'trinket',
    icon: 'circle',
    rewardKind: 'simple',
    defCoeff: 0.1,
    dodgeBonus: 4,
    effects: [
      { kind: 'defCoeff', value: 10, unit: 'percent', description: '+10% к коэфф. защиты' },
      { kind: 'dodge', value: 4, unit: 'percent', description: '+4% к уклонению' },
    ],
  },
  {
    id: 'rhythm-charm',
    name: 'Амулет ритма',
    shortName: 'Ритм',
    description: 'Повышает шанс крита. Ровный темп — ключ к мощи.',
    rarity: 2,
    slotType: 'trinket',
    icon: 'activity',
    rewardKind: 'simple',
    critBonus: 0.05,
    effects: [
      { kind: 'critBonus', value: 5, unit: 'percent', description: '+5% к шансу крита' },
    ],
  },
  {
    id: 'precision-lens',
    name: 'Линза точного удара',
    shortName: 'Точность',
    description: 'Бонус крита и атаки игрока.',
    rarity: 2,
    slotType: 'trinket',
    icon: 'crosshair',
    rewardKind: 'simple',
    critBonus: 0.03,
    playerAttackBonus: 5,
    effects: [
      { kind: 'critBonus', value: 3, unit: 'percent', description: '+3% к шансу крита' },
      { kind: 'playerAttack', value: 5, unit: 'percent', description: '+5% к шансу попасть' },
    ],
  },
  {
    id: 'crusher-seal',
    name: 'Печать сокрушителя',
    shortName: 'Сокрушитель',
    description: 'Плоский урон и снижение защиты врагов.',
    rarity: 3,
    slotType: 'trinket',
    icon: 'shield-off',
    rewardKind: 'simple',
    playerDamageBonus: 2,
    enemyDefenseReduction: 5,
    effects: [
      { kind: 'playerDamage', value: 2, unit: 'flat', description: '+2 к плоскому урону' },
      { kind: 'enemyDefense', value: 5, unit: 'flat', description: '-5 к защите врагов' },
    ],
  },
  {
    id: 'heavy-strike',
    name: 'Тяжёлый удар',
    shortName: 'Удар',
    description: 'Добавляет плоский урон и немного усиливает коэффициент.',
    rarity: 2,
    slotType: 'trinket',
    icon: 'hammer',
    rewardKind: 'simple',
    playerDamageBonus: 1,
    dmgCoeff: 0.08,
    effects: [
      { kind: 'playerDamage', value: 1, unit: 'flat', description: '+1 к плоскому урону' },
      { kind: 'dmgCoeff', value: 8, unit: 'percent', description: '+8% к коэфф. урона' },
    ],
  },

  // ═══════════════════════════════════════════════
  //  Прочные (durable) артефакты — с износом
  // ═══════════════════════════════════════════════

  // ── Утилити: скорость / точность / таймер ──
  {
    id: 'rift-hourglass',
    name: 'Разломные песочные часы',
    shortName: 'Разлом',
    description: 'Резко упрощает боссов: таймер и урон по ним, но быстро трескается.',
    rarity: 3,
    slotType: 'trinket',
    icon: 'timer',
    rewardKind: 'durable',
    bossOnly: true,
    bossTimerBonusSeconds: 10,
    dmgCoeff: 0.15,
    maxDurability: 4,
    durabilityRules: { normalPass: 0, normalFail: 0, bossPass: 1, bossFail: 2 },
    effects: [
      { kind: 'timer', value: 10, unit: 'seconds', description: '+10 сек. к таймеру босса' },
      { kind: 'dmgCoeff', value: 15, unit: 'percent', description: '+15% к коэфф. урона' },
    ],
  },
  {
    id: 'storm-anchor',
    name: 'Штормовой якорь',
    shortName: 'Якорь',
    description: 'Боссовый артефакт: таймер и коэффициент защиты.',
    rarity: 2,
    slotType: 'trinket',
    icon: 'anchor',
    rewardKind: 'durable',
    bossOnly: true,
    bossTimerBonusSeconds: 6,
    defCoeff: 0.12,
    maxDurability: 5,
    durabilityRules: { normalPass: 0, normalFail: 0, bossPass: 1, bossFail: 1 },
    effects: [
      { kind: 'timer', value: 6, unit: 'seconds', description: '+6 сек. к таймеру босса' },
      { kind: 'defCoeff', value: 12, unit: 'percent', description: '+12% к коэфф. защиты' },
    ],
  },
  {
    id: 'overclock-core',
    name: 'Ядро разгона',
    shortName: 'Разгон',
    description: 'Мощная скорость и коэффициент урона. Изнашивается почти каждый уровень.',
    rarity: 3,
    slotType: 'trinket',
    icon: 'zap',
    rewardKind: 'durable',
    speedRequirementReductionPercent: 16,
    dmgCoeff: 0.2,
    maxDurability: 6,
    durabilityRules: { normalPass: 1, normalFail: 2, bossPass: 1, bossFail: 2 },
    effects: [
      { kind: 'speed', value: 16, unit: 'percent', description: '-16% к требуемой скорости' },
      { kind: 'dmgCoeff', value: 20, unit: 'percent', description: '+20% к коэфф. урона' },
    ],
  },
  {
    id: 'brain-lattice',
    name: 'Мозговая решетка',
    shortName: 'Решетка',
    description: 'Точность, атака игрока и крит. Ломается после провалов.',
    rarity: 3,
    slotType: 'trinket',
    icon: 'brain',
    rewardKind: 'durable',
    accuracyRequirementReduction: 8,
    playerAttackBonus: 6,
    critBonus: 0.04,
    maxDurability: 5,
    durabilityRules: { normalPass: 1, normalFail: 2, bossPass: 1, bossFail: 2 },
    effects: [
      { kind: 'accuracy', value: 8, unit: 'percent', description: '-8% к требуемой точности' },
      { kind: 'playerAttack', value: 6, unit: 'percent', description: '+6% к шансу попасть' },
      { kind: 'critBonus', value: 4, unit: 'percent', description: '+4% к шансу крита' },
    ],
  },
  {
    id: 'aegis-prism',
    name: 'Призма эгиды',
    shortName: 'Эгида',
    description: 'Точность, таймер и сильный коэффициент защиты.',
    rarity: 2,
    slotType: 'trinket',
    icon: 'shield',
    rewardKind: 'durable',
    accuracyRequirementReduction: 6,
    bossTimerBonusSeconds: 3,
    defCoeff: 0.18,
    maxDurability: 5,
    durabilityRules: { normalPass: 0, normalFail: 1, bossPass: 1, bossFail: 2 },
    effects: [
      { kind: 'accuracy', value: 6, unit: 'percent', description: '-6% к требуемой точности' },
      { kind: 'timer', value: 3, unit: 'seconds', description: '+3 сек. к таймеру босса' },
      { kind: 'defCoeff', value: 18, unit: 'percent', description: '+18% к коэфф. защиты' },
    ],
  },
  {
    id: 'spark-capsule',
    name: 'Искровая капсула',
    shortName: 'Искра',
    description: 'Мощный боссовый буст: скорость, таймер и крит.',
    rarity: 3,
    slotType: 'trinket',
    icon: 'sparkles',
    rewardKind: 'durable',
    bossOnly: true,
    speedRequirementReductionPercent: 8,
    bossTimerBonusSeconds: 4,
    critBonus: 0.06,
    maxDurability: 3,
    durabilityRules: { normalPass: 0, normalFail: 0, bossPass: 1, bossFail: 2 },
    effects: [
      { kind: 'speed', value: 8, unit: 'percent', description: '-8% к скорости на боссе' },
      { kind: 'timer', value: 4, unit: 'seconds', description: '+4 сек. к таймеру босса' },
      { kind: 'critBonus', value: 6, unit: 'percent', description: '+6% к шансу крита' },
    ],
  },
  {
    id: 'warden-lock',
    name: 'Замок хранителя',
    shortName: 'Замок',
    description: 'Точность и мощная защита, но жёсткое наказание за провалы.',
    rarity: 2,
    slotType: 'trinket',
    icon: 'lock',
    rewardKind: 'durable',
    accuracyRequirementReduction: 5,
    defCoeff: 0.15,
    enemyAttackReduction: 3,
    maxDurability: 4,
    durabilityRules: { normalPass: 0, normalFail: 2, bossPass: 1, bossFail: 2 },
    effects: [
      { kind: 'accuracy', value: 5, unit: 'percent', description: '-5% к требуемой точности' },
      { kind: 'defCoeff', value: 15, unit: 'percent', description: '+15% к коэфф. защиты' },
      { kind: 'enemyAttack', value: 3, unit: 'flat', description: '-3 к шансу попадания врагов' },
    ],
  },
  {
    id: 'ember-seal',
    name: 'Печать перегрева',
    shortName: 'Перегрев',
    description: 'Мощный буст скорости, точности и урона. Выгорает мгновенно.',
    rarity: 3,
    slotType: 'trinket',
    icon: 'flame',
    rewardKind: 'durable',
    speedRequirementReductionPercent: 9,
    accuracyRequirementReduction: 4,
    dmgCoeff: 0.15,
    maxDurability: 3,
    durabilityRules: { normalPass: 1, normalFail: 2, bossPass: 1, bossFail: 2 },
    effects: [
      { kind: 'speed', value: 9, unit: 'percent', description: '-9% к требуемой скорости' },
      { kind: 'accuracy', value: 4, unit: 'percent', description: '-4% к требуемой точности' },
      { kind: 'dmgCoeff', value: 15, unit: 'percent', description: '+15% к коэфф. урона' },
    ],
  },
  {
    id: 'loaded-die',
    name: 'Загруженная кость',
    shortName: 'Кость',
    description: 'Скорость, точность и шанс крита. Азартный рывок.',
    rarity: 3,
    slotType: 'trinket',
    icon: 'dice',
    rewardKind: 'durable',
    speedRequirementReductionPercent: 10,
    accuracyRequirementReduction: 3,
    critBonus: 0.06,
    maxDurability: 4,
    durabilityRules: { normalPass: 1, normalFail: 2, bossPass: 1, bossFail: 2 },
    effects: [
      { kind: 'speed', value: 10, unit: 'percent', description: '-10% к требуемой скорости' },
      { kind: 'accuracy', value: 3, unit: 'percent', description: '-3% к требуемой точности' },
      { kind: 'critBonus', value: 6, unit: 'percent', description: '+6% к шансу крита' },
    ],
  },
  {
    id: 'wand-of-blinks',
    name: 'Жезл вспышек',
    shortName: 'Жезл',
    description: 'Сильнейший боссовый артефакт: скорость, точность и урон.',
    rarity: 3,
    slotType: 'trinket',
    icon: 'wand',
    rewardKind: 'durable',
    bossOnly: true,
    speedRequirementReductionPercent: 6,
    accuracyRequirementReduction: 5,
    dmgCoeff: 0.2,
    maxDurability: 3,
    durabilityRules: { normalPass: 0, normalFail: 0, bossPass: 1, bossFail: 2 },
    effects: [
      { kind: 'speed', value: 6, unit: 'percent', description: '-6% к скорости на боссе' },
      { kind: 'accuracy', value: 5, unit: 'percent', description: '-5% к точности на боссе' },
      { kind: 'dmgCoeff', value: 20, unit: 'percent', description: '+20% к коэфф. урона' },
    ],
  },

  // ── Боевые прочные ──
  {
    id: 'razorblade-edge',
    name: 'Бритвенное лезвие',
    shortName: 'Лезвие',
    description: 'Снижает защиту врагов и повышает коэффициент урона. Крошится при неудачах.',
    rarity: 3,
    slotType: 'trinket',
    icon: 'axe',
    rewardKind: 'durable',
    enemyDefenseReduction: 8,
    dmgCoeff: 0.12,
    maxDurability: 4,
    durabilityRules: { normalPass: 0, normalFail: 1, bossPass: 1, bossFail: 2 },
    effects: [
      { kind: 'enemyDefense', value: 8, unit: 'flat', description: '-8 к защите врагов' },
      { kind: 'dmgCoeff', value: 12, unit: 'percent', description: '+12% к коэфф. урона' },
    ],
  },
  {
    id: 'guardian-ward',
    name: 'Тотем стража',
    shortName: 'Тотем',
    description: 'Снижает атаку врагов и усиливает коэффициент защиты.',
    rarity: 3,
    slotType: 'trinket',
    icon: 'pillar',
    rewardKind: 'durable',
    enemyAttackReduction: 8,
    defCoeff: 0.15,
    maxDurability: 4,
    durabilityRules: { normalPass: 0, normalFail: 1, bossPass: 1, bossFail: 2 },
    effects: [
      { kind: 'enemyAttack', value: 8, unit: 'flat', description: '-8 к шансу попадания врагов' },
      { kind: 'defCoeff', value: 15, unit: 'percent', description: '+15% к коэфф. защиты' },
    ],
  },
  {
    id: 'shadow-mantle',
    name: 'Мантия теней',
    shortName: 'Мантия',
    description: 'Мощное уклонение и крит, но быстро истощается.',
    rarity: 3,
    slotType: 'trinket',
    icon: 'eclipse',
    rewardKind: 'durable',
    dodgeBonus: 10,
    critBonus: 0.05,
    maxDurability: 4,
    durabilityRules: { normalPass: 1, normalFail: 2, bossPass: 1, bossFail: 2 },
    effects: [
      { kind: 'dodge', value: 10, unit: 'percent', description: '+10% к уклонению' },
      { kind: 'critBonus', value: 5, unit: 'percent', description: '+5% к шансу крита' },
    ],
  },
  {
    id: 'war-talisman',
    name: 'Боевой талисман',
    shortName: 'Талисман',
    description: 'Универсальный боевой артефакт: атака и защита врагов, плюс урон.',
    rarity: 3,
    slotType: 'trinket',
    icon: 'shield-alert',
    rewardKind: 'durable',
    enemyAttackReduction: 4,
    enemyDefenseReduction: 4,
    dmgCoeff: 0.1,
    maxDurability: 5,
    durabilityRules: { normalPass: 0, normalFail: 1, bossPass: 1, bossFail: 2 },
    effects: [
      { kind: 'enemyAttack', value: 4, unit: 'flat', description: '-4 к шансу попадания врагов' },
      { kind: 'enemyDefense', value: 4, unit: 'flat', description: '-4 к защите врагов' },
      { kind: 'dmgCoeff', value: 10, unit: 'percent', description: '+10% к коэфф. урона' },
    ],
  },
  {
    id: 'bloodletter',
    name: 'Кровопускатель',
    shortName: 'Кровник',
    description: 'Атака, урон и крит. Изнашивается от провалов.',
    rarity: 3,
    slotType: 'trinket',
    icon: 'flame',
    rewardKind: 'durable',
    playerAttackBonus: 10,
    dmgCoeff: 0.15,
    critBonus: 0.03,
    maxDurability: 4,
    durabilityRules: { normalPass: 0, normalFail: 1, bossPass: 1, bossFail: 2 },
    effects: [
      { kind: 'playerAttack', value: 10, unit: 'percent', description: '+10% к шансу попасть' },
      { kind: 'dmgCoeff', value: 15, unit: 'percent', description: '+15% к коэфф. урона' },
      { kind: 'critBonus', value: 3, unit: 'percent', description: '+3% к шансу крита' },
    ],
  },
  {
    id: 'war-drum',
    name: 'Боевой барабан',
    shortName: 'Барабан',
    description: 'Мощный боссовый артефакт: атака и коэффициент урона.',
    rarity: 3,
    slotType: 'trinket',
    icon: 'radio',
    rewardKind: 'durable',
    bossOnly: true,
    playerAttackBonus: 12,
    dmgCoeff: 0.2,
    maxDurability: 3,
    durabilityRules: { normalPass: 0, normalFail: 0, bossPass: 1, bossFail: 2 },
    effects: [
      { kind: 'playerAttack', value: 12, unit: 'percent', description: '+12% к шансу попасть по боссу' },
      { kind: 'dmgCoeff', value: 20, unit: 'percent', description: '+20% к коэфф. урона' },
    ],
  },
  {
    id: 'titan-gauntlet',
    name: 'Перчатка титана',
    shortName: 'Перчатка',
    description: 'Огромный плоский урон и коэффициент урона. Хрупкая.',
    rarity: 3,
    slotType: 'trinket',
    icon: 'hand',
    rewardKind: 'durable',
    playerDamageBonus: 3,
    dmgCoeff: 0.15,
    maxDurability: 4,
    durabilityRules: { normalPass: 0, normalFail: 1, bossPass: 1, bossFail: 2 },
    effects: [
      { kind: 'playerDamage', value: 3, unit: 'flat', description: '+3 к плоскому урону' },
      { kind: 'dmgCoeff', value: 15, unit: 'percent', description: '+15% к коэфф. урона' },
    ],
  },
  {
    id: 'boss-slayer',
    name: 'Убийца боссов',
    shortName: 'Слэйер',
    description: 'Только против боссов: плоский урон, коэффициент и крит.',
    rarity: 3,
    slotType: 'trinket',
    icon: 'skull',
    rewardKind: 'durable',
    bossOnly: true,
    playerDamageBonus: 3,
    dmgCoeff: 0.18,
    critBonus: 0.04,
    maxDurability: 3,
    durabilityRules: { normalPass: 0, normalFail: 0, bossPass: 1, bossFail: 2 },
    effects: [
      { kind: 'playerDamage', value: 3, unit: 'flat', description: '+3 к плоскому урону по боссам' },
      { kind: 'dmgCoeff', value: 18, unit: 'percent', description: '+18% к коэфф. урона' },
      { kind: 'critBonus', value: 4, unit: 'percent', description: '+4% к шансу крита' },
    ],
  },
  {
    id: 'berserk-core',
    name: 'Ядро берсерка',
    shortName: 'Берсерк',
    description: 'Огромный коэффициент урона и атака. Быстро изнашивается.',
    rarity: 3,
    slotType: 'trinket',
    icon: 'zap',
    rewardKind: 'durable',
    dmgCoeff: 0.35,
    playerAttackBonus: 6,
    maxDurability: 4,
    durabilityRules: { normalPass: 1, normalFail: 2, bossPass: 1, bossFail: 2 },
    effects: [
      { kind: 'dmgCoeff', value: 35, unit: 'percent', description: '+35% к коэфф. урона' },
      { kind: 'playerAttack', value: 6, unit: 'percent', description: '+6% к шансу попасть' },
    ],
  },
  {
    id: 'fortress-plate',
    name: 'Пластина крепости',
    shortName: 'Крепость',
    description: 'Массивная защита и снижение атаки врагов. Не выдержит долгого похода.',
    rarity: 3,
    slotType: 'trinket',
    icon: 'castle',
    rewardKind: 'durable',
    defCoeff: 0.35,
    enemyAttackReduction: 5,
    maxDurability: 4,
    durabilityRules: { normalPass: 1, normalFail: 2, bossPass: 1, bossFail: 2 },
    effects: [
      { kind: 'defCoeff', value: 35, unit: 'percent', description: '+35% к коэфф. защиты' },
      { kind: 'enemyAttack', value: 5, unit: 'flat', description: '-5 к шансу попадания врагов' },
    ],
  },
  {
    id: 'lucky-die',
    name: 'Счастливая кость',
    shortName: 'Удача',
    description: 'Мощный крит и бонус урона. Удача непостоянна.',
    rarity: 3,
    slotType: 'trinket',
    icon: 'dice',
    rewardKind: 'durable',
    critBonus: 0.12,
    dmgCoeff: 0.1,
    maxDurability: 4,
    durabilityRules: { normalPass: 0, normalFail: 1, bossPass: 1, bossFail: 2 },
    effects: [
      { kind: 'critBonus', value: 12, unit: 'percent', description: '+12% к шансу крита' },
      { kind: 'dmgCoeff', value: 10, unit: 'percent', description: '+10% к коэфф. урона' },
    ],
  },
];

export const GAME_ITEM_MAP = Object.fromEntries(
  GAME_ITEM_CATALOG.map(item => [item.id, item]),
) as Record<string, GameItemDefinition>;

export const GAME_ITEM_POOLS: Record<GameItemRewardKind, GameItemDefinition[]> = {
  simple: GAME_ITEM_CATALOG.filter(item => item.rewardKind === 'simple'),
  durable: GAME_ITEM_CATALOG.filter(item => item.rewardKind === 'durable'),
};

export const GAME_EQUIPMENT_SLOTS: Array<{
  key: GameEquipmentSlot;
  label: string;
  slotType: GameItemDefinition['slotType'];
}> = [
  { key: 'slotA', label: 'Слот 1', slotType: 'trinket' },
  { key: 'slotB', label: 'Слот 2', slotType: 'trinket' },
  { key: 'slotC', label: 'Слот 3', slotType: 'trinket' },
];
